- name: cron letsencrypt
  cron: name="letsencrypt" 
    minute="0" 
    hour="5" 
    job="/etc/letsencrypt/certbot-auto renew"

- name: copy crontab
  copy:
    src: "{{ item.src }}"
    dest: "/etc/{{ item.dest }}"
    backup: no
    owner: root
    group: root
  loop:
    - { src: roles/cron/files/crontab, dest: . }

